=== KiranBedre/osdu-spi-rafs-ddms/app/models/data_schemas/jsonschema/api_v2/transport.1.0.0.json
{
  "x-osdu-license": "Copyright 2025, The Open Group \\nLicensed under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.",
  "x-osdu-review-status": "Mature",
  "$id": "transport.1.0.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Transport Test Data Schema",
  "description": "The Transport Test is to assess the properties of the fluid relevant to transportation. A series of test steps for properties (such as viscosity, density, etc.) can be defined.",
  "type": "object",
  "properties": {
    "SamplesAnalysisID": {
      "type": "string",
      "title": "Samples Analysis ID",
      "description": "The OSDU Identifier for this SamplesAnalysis.",
      "pattern": "^[\\w\\-\\.]+:work-product-component\\-\\-SamplesAnalysis:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "GroupType": "work-product-component",
          "EntityType": "SamplesAnalysis"
        }
      ]
    },
    "SampleID": {
      "type": "string",
      "title": "Sample ID",
      "description": "The OSDU Identifier for the Sample associated with this analysis.",
      "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Sample:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "GroupType": "master-data",
          "EntityType": "Sample"
        }
      ]
    },
    "Meta": {
      "type": "array",
      "title": "Meta",
      "description": "A meta data item, which allows the association of named properties or property values to a Unit/Measurement/CRS/Azimuth/Time context.",
      "example": "",
      "items": {
        "x-osdu-license": "Copyright 2022, The Open Group \\nLicensed under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.",
        "$id": "https://schema.osdu.opengroup.org/json/abstract/AbstractMetaItem.1.0.0.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "x-osdu-schema-source": "osdu:wks:AbstractMetaItem:1.0.0",
        "title": "Frame of Reference Meta Data Item",
        "description": "A meta data item, which allows the association of named properties or property values to a Unit/Measurement/CRS/Azimuth/Time context.",
        "oneOf": [
          {
            "title": "FrameOfReferenceUOM",
            "type": "object",
            "properties": {
              "kind": {
                "title": "UOM Reference Kind",
                "type": "string",
                "description": "The kind of reference, 'Unit' for FrameOfReferenceUOM.",
                "const": "Unit"
              },
              "name": {
                "title": "UOM Unit Symbol",
                "description": "The unit symbol or name of the unit.",
                "type": "string",
                "example": "ft[US]"
              },
              "persistableReference": {
                "title": "UOM Persistable Reference",
                "description": "The self-contained, persistable reference string uniquely identifying the Unit.",
                "type": "string",
                "example": "{\"abcd\":{\"a\":0.0,\"b\":1200.0,\"c\":3937.0,\"d\":0.0},\"symbol\":\"ft[US]\",\"baseMeasurement\":{\"ancestry\":\"L\",\"type\":\"UM\"},\"type\":\"UAD\"}"
              },
              "unitOfMeasureID": {
                "description": "SRN to unit of measure reference.",
                "type": "string",
                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                "example": "namespace:reference-data--UnitOfMeasure:ftUS:",
                "x-osdu-relationship": [
                  {
                    "GroupType": "reference-data",
                    "EntityType": "UnitOfMeasure"
                  }
                ]
              },
              "propertyNames": {
                "title": "UOM Property Names",
                "description": "The list of property names, to which this meta data item provides Unit context to. A full path like \"StructureA.PropertyB\" is required to define a unique context; \"data\" is omitted since frame-of reference normalization only applies to the data block.",
                "type": "array",
                "example": [
                  "HorizontalDeflection.EastWest",
                  "HorizontalDeflection.NorthSouth"
                ],
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "kind",
              "persistableReference"
            ]
          },
          {
            "title": "FrameOfReferenceCRS",
            "type": "object",
            "properties": {
              "kind": {
                "title": "CRS Reference Kind",
                "type": "string",
                "description": "The kind of reference, constant 'CRS' for FrameOfReferenceCRS.",
                "const": "CRS"
              },
              "name": {
                "title": "CRS Name",
                "description": "The name of the CRS.",
                "type": "string",
                "example": "WGS 84 / UTM zone 15N"
              },
              "persistableReference": {
                "title": "CRS Persistable Reference",
                "description": "The self-contained, persistable reference string uniquely identifying the CRS.",
                "type": "string",
                "example": "{\"authCode\":{\"auth\":\"EPSG\",\"code\":\"32615\"},\"name\":\"WGS_1984_UTM_Zone_15N\",\"type\":\"LBC\",\"ver\":\"PE_10_9_1\",\"wkt\":\"PROJCS[\\\"WGS_1984_UTM_Zone_15N\\\",GEOGCS[\\\"GCS_WGS_1984\\\",DATUM[\\\"D_WGS_1984\\\",SPHEROID[\\\"WGS_1984\\\",6378137.0,298.257223563]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],PROJECTION[\\\"Transverse_Mercator\\\"],PARAMETER[\\\"False_Easting\\\",500000.0],PARAMETER[\\\"False_Northing\\\",0.0],PARAMETER[\\\"Central_Meridian\\\",-93.0],PARAMETER[\\\"Scale_Factor\\\",0.9996],PARAMETER[\\\"Latitude_Of_Origin\\\",0.0],UNIT[\\\"Meter\\\",1.0],AUTHORITY[\\\"EPSG\\\",32615]]\"}"
              },
              "coordinateReferenceSystemID": {
                "description": "SRN to CRS reference.",
                "type": "string",
                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-CoordinateReferenceSystem:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                "example": "namespace:reference-data--CoordinateReferenceSystem:Projected:EPSG::32615:",
                "x-osdu-relationship": [
                  {
                    "GroupType": "reference-data",
                    "EntityType": "CoordinateReferenceSystem"
                  }
                ]
              },
              "propertyNames": {
                "title": "CRS Property Names",
                "description": "The list of property names, to which this meta data item provides CRS context to. A full path like \"StructureA.PropertyB\" is required to define a unique context; \"data\" is omitted since frame-of reference normalization only applies to the data block.",
                "type": "array",
                "example": [
                  "KickOffPosition.X",
                  "KickOffPosition.Y"
                ],
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "kind",
              "persistableReference"
            ]
          },
          {
            "title": "FrameOfReferenceDateTime",
            "type": "object",
            "properties": {
              "kind": {
                "title": "DateTime Reference Kind",
                "type": "string",
                "description": "The kind of reference, constant 'DateTime', for FrameOfReferenceDateTime.",
                "const": "DateTime"
              },
              "name": {
                "title": "DateTime Name",
                "description": "The name of the DateTime format and reference.",
                "type": "string",
                "example": "UTC"
              },
              "persistableReference": {
                "title": "DateTime Persistable Reference",
                "description": "The self-contained, persistable reference string uniquely identifying DateTime reference.",
                "type": "string",
                "example": "{\"format\":\"yyyy-MM-ddTHH:mm:ssZ\",\"timeZone\":\"UTC\",\"type\":\"DTM\"}"
              },
              "propertyNames": {
                "title": "DateTime Property Names",
                "description": "The list of property names, to which this meta data item provides DateTime context to. A full path like \"StructureA.PropertyB\" is required to define a unique context; \"data\" is omitted since frame-of reference normalization only applies to the data block.",
                "type": "array",
                "example": [
                  "Acquisition.StartTime",
                  "Acquisition.EndTime"
                ],
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "kind",
              "persistableReference"
            ]
          },
          {
            "title": "FrameOfReferenceAzimuthReference",
            "type": "object",
            "properties": {
              "kind": {
                "title": "AzimuthReference Reference Kind",
                "type": "string",
                "description": "The kind of reference, constant 'AzimuthReference', for FrameOfReferenceAzimuthReference.",
                "const": "AzimuthReference"
              },
              "name": {
                "title": "AzimuthReference Name",
                "description": "The name of the CRS or the symbol/name of the unit.",
                "type": "string",
                "example": "TrueNorth"
              },
              "persistableReference": {
                "title": "AzimuthReference Persistable Reference",
                "description": "The self-contained, persistable reference string uniquely identifying AzimuthReference.",
                "type": "string",
                "example": "{\"code\":\"TrueNorth\",\"type\":\"AZR\"}"
              },
              "propertyNames": {
                "title": "AzimuthReference Property Names",
                "description": "The list of property names, to which this meta data item provides AzimuthReference context to. A full path like \"StructureA.PropertyB\" is required to define a unique context; \"data\" is omitted since frame-of reference normalization only applies to the data block.",
                "type": "array",
                "example": [
                  "Bearing"
                ],
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "kind",
              "persistableReference"
            ]
          }
        ],
        "x-osdu-inheriting-from-kind": []
      }
    },
    "TestNumber": {
      "type": "string",
      "title": "Test Number",
      "description": "A number for this test for purposes of e.g., tracking lab sequence."
    },
    "ReservoirPressure": {
      "type": "number",
      "title": "Reservoir Pressure",
      "description": "The pressure conditions of the reservoir where the sample was collected.",
      "x-osdu-frame-of-reference": "UOM:pressure"
    },
    "ViscosityMethodID": {
      "type": "string",
      "title": "Viscosity Method ID",
      "description": "Identifier for the method by which viscosity was measured or calculated.",
      "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-ViscosityMethod:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "GroupType": "reference-data",
          "EntityType": "ViscosityMethod"
        }
      ]
    },
    "TestSteps": {
      "type": "array",
      "title": "Test Steps",
      "description": "The test steps for this viscosity test.",
      "x-osdu-indexing": {
        "type": "nested"
      },
      "items": {
        "type": "object",
        "title": "Test Steps",
        "description": "The test steps for this viscosity test.",
        "properties": {
          "StepNumber": {
            "type": "string",
            "title": "Step Number",
            "description": "Internal step number which identifies the sequence of step in transport test measurements."
          },
          "StepPressure": {
            "type": "number",
            "title": "Step Pressure",
            "description": "The pressure condition recorded at this test step.",
            "x-osdu-frame-of-reference": "UOM:pressure"
          },
          "StepTemperature": {
            "type": "number",
            "title": "Step Temperature",
            "description": "The temperature recorded at this test step.",
            "x-osdu-frame-of-reference": "UOM:thermodynamic temperature"
          },
          "OilViscosity": {
            "type": "number",
            "title": "Oil Viscosity",
            "description": "A measure of a fluid’s internal resistance to flow.",
            "x-osdu-frame-of-reference": "UOM:dynamic viscosity"
          },
          "GasViscosity": {
            "type": "number",
            "title": "Gas Viscosity",
            "description": "A measure of a fluid’s internal resistance to flow.",
            "x-osdu-frame-of-reference": "UOM:dynamic viscosity"
          },
          "FluidPhasesPresentID": {
            "type": "string",
            "title": "Fluid Phases Present ID",
            "description": "Identifies the phases of fluid present in the sample, e.g. SeparatorLiquid, FlashedOil, OilWithMud, Gas, ReservoirFluid (references FluidPhasesPresent).",
            "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-FluidPhasesPresent:[\\w\\-\\.\\:\\%]+:[0-9]*$",
            "x-osdu-relationship": [
              {
                "GroupType": "reference-data",
                "EntityType": "FluidPhasesPresent"
              }
            ]
          },
          "SaturationPressure": {
            "type": "number",
            "title": "Saturation Pressure",
            "description": "The saturation (or bubble point) pressure at the Step Temperature in this test step.",
            "x-osdu-frame-of-reference": "UOM:pressure"
          },
          "Remarks": {
            "type": "array",
            "title": "Remarks",
            "description": "Array object capturing remarks or additional information for this test step.  Remarks for the analysis as a whole should be captured in the associated SamplesAnalysis work product component.",
            "example": "",
            "x-osdu-indexing": {
              "type": "nested"
            },
            "items": {
              "x-osdu-license": "Copyright 2023, The Open Group \\nLicensed under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.",
              "x-osdu-review-status": "Accepted",
              "$id": "https://schema.osdu.opengroup.org/json/abstract/AbstractRemark.1.0.0.json",
              "$schema": "http://json-schema.org/draft-07/schema#",
              "x-osdu-schema-source": "osdu:wks:AbstractRemark:1.0.0",
              "title": "AbstractRemark",
              "description": "A remark object, pairing a remark text with a source, e.g. an author, and a date, which is typically included in an array. The RemarkSequenceNumber acts as unique key in this case.",
              "type": "object",
              "properties": {
                "RemarkSequenceNumber": {
                  "type": "integer",
                  "title": "Remark Sequence Number",
                  "description": "A unique identifier for each remark record. This identifier is used to uniquely identify a member in an array of remarks.",
                  "example": 1
                },
                "Remark": {
                  "type": "string",
                  "title": "Remark",
                  "description": "A descriptive comment for this remark."
                },
                "RemarkSource": {
                  "type": "string",
                  "title": "Remark Source",
                  "description": "The person, vendor, interpreter or other provider of information."
                },
                "RemarkDate": {
                  "type": "string",
                  "title": "Remark Date",
                  "description": "The date the remark was issued.",
                  "format": "date",
                  "x-osdu-frame-of-reference": "DateTime"
                }
              },
              "x-osdu-inheriting-from-kind": [],
              "additionalProperties": false
            }
          },
          "OilDensity": {
            "type": "number",
            "title": "Oil Density",
            "description": "The mass per volume of oil in the sample.",
            "x-osdu-frame-of-reference": "UOM:mass per volume"
          },
          "GasDensity": {
            "type": "number",
            "title": "Gas Density",
            "description": "The mass per volume of gas in the sample.",
            "x-osdu-frame-of-reference": "UOM:mass per volume"
          }
        },
        "additionalProperties": false
      }
    },
    "AssociatedAnalysisTypeID": {
      "type": "string",
      "title": "Associated Analysis Type ID",
      "description": "The type of flash process through which the gas and liquid phases are separated, e.g. Differential Liberation, Constant Composition Expansion, Constant Volume Depletion, Atmospheric Flash.",
      "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-SampleAnalysisType:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "GroupType": "reference-data",
          "EntityType": "SampleAnalysisType"
        }
      ]
    }
  },
  "required": [
    "SamplesAnalysisID",
    "SampleID",
    "Meta"
  ],
  "additionalProperties": false
}

=== KiranBedre/osdu-spi-rafs-ddms/app/models/data_schemas/jsonschema/api_v2/transport_example.1.0.0.json
[
  {
    "SamplesAnalysisID": "opendes:work-product-component--SamplesAnalysis:Example_WPC:",
    "SampleID": "opendes:master-data--Sample:Example_Sample:",
    "Meta": [
          {
            "kind": "Unit",
            "name": "pound-force per square inch",
            "persistableReference": "{\"abcd\":{\"a\":0.0,\"b\":4.4482216152605,\"c\":6.4516E-4,\"d\":0.0},\"symbol\":\"psi\",\"baseMeasurement\":{\"ancestry\":\"M/LT2\",\"type\":\"UM\"},\"type\":\"UAD\"}",
            "unitOfMeasureID": "opendes:reference-data--UnitOfMeasure:psi:",
            "propertyNames": [
              "ReservoirPressure"
            ]
          }
    ],
    "TestNumber": "1A",
    "ReservoirPressure": 1.23,
    "ViscosityMethodID": "opendes:reference-data--ViscosityMethod:CambridgeElectromagneticViscometer:",
    "TestSteps": [
      {
        "StepNumber": "1A",
        "StepPressure": 1.23,
        "StepTemperature": 1.23,
        "OilViscosity": 1.23,
        "GasViscosity": 1.23,
        "FluidPhasesPresentID": "opendes:reference-data--FluidPhasesPresent:Water:",
        "SaturationPressure": 1.23
      },
      {
        "StepNumber": "2A",
        "StepPressure": 1.23,
        "StepTemperature": 1.23,
        "OilViscosity": 1.23,
        "GasViscosity": 1.23,
        "FluidPhasesPresentID": "opendes:reference-data--FluidPhasesPresent:Wellstream:",
        "SaturationPressure": 1.23
      }
    ],
    "AssociatedAnalysisTypeID": "opendes:reference-data--SampleAnalysisType:BasicRockProperties.CrushedRockAnalysis:"
  }
]
