=== KiranBedre/osdu-spi-rafs-ddms/deployments/shared-schemas/osdu/reference-data/DepthShiftInterpolationMethod.1.0.0.json
{
  "x-osdu-license": "Copyright 2026, The Open Group \\nLicensed under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.",
  "$id": "https://schema.osdu.opengroup.org/json/reference-data/DepthShiftInterpolationMethod.1.0.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "x-osdu-schema-source": "osdu:wks:reference-data--DepthShiftInterpolationMethod:1.0.0",
  "title": "DepthShiftInterpolationMethod",
  "description": "Identifies the method of interpolation to be used with a depth shift when the distance between original depths differs from the distance between shifted depths (e.g., None, Linear, Bilinear).",
  "type": "object",
  "properties": {
    "id": {
      "description": "Previously called ResourceID or SRN which identifies this OSDU resource object without version.",
      "title": "Entity ID",
      "type": "string",
      "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-DepthShiftInterpolationMethod:[\\w\\-\\.\\:\\%]+$",
      "example": "namespace:reference-data--DepthShiftInterpolationMethod:1cada729-26a0-53eb-b1b5-56c8280463cc"
    },
    "kind": {
      "description": "The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.",
      "title": "Entity Kind",
      "type": "string",
      "pattern": "^[\\w\\-\\.]+:[\\w\\-\\.]+:[\\w\\-\\.]+:[0-9]+.[0-9]+.[0-9]+$",
      "example": "osdu:wks:reference-data--DepthShiftInterpolationMethod:1.0.0"
    },
    "version": {
      "description": "The version number of this OSDU resource; set by the framework.",
      "title": "Version Number",
      "type": "integer",
      "format": "int64",
      "example": 1562066009929332
    },
    "acl": {
      "description": "The access control tags associated with this entity.",
      "title": "Access Control List",
      "$ref": "osdu:wks:AbstractAccessControlList:1.0.0"
    },
    "legal": {
      "description": "The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
      "title": "Legal Tags",
      "$ref": "osdu:wks:AbstractLegalTags:1.0.0"
    },
    "tags": {
      "title": "Tag Dictionary",
      "description": "A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "example": {
        "NameOfKey": "String value"
      }
    },
    "createTime": {
      "description": "Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
      "title": "Resource Object Creation DateTime",
      "type": "string",
      "format": "date-time",
      "example": "2020-12-16T11:46:20.163Z"
    },
    "createUser": {
      "title": "Resource Object Creation User Reference",
      "description": "The user reference, which created the first version of this resource object. Set by the System.",
      "type": "string",
      "example": "some-user@some-company-cloud.com"
    },
    "modifyTime": {
      "description": "Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
      "title": "Resource Object Version Creation DateTime",
      "type": "string",
      "format": "date-time",
      "example": "2020-12-16T11:52:24.477Z"
    },
    "modifyUser": {
      "title": "Resource Object Version Creation User Reference",
      "description": "The user reference, which created this version of this resource object. Set by the System.",
      "type": "string",
      "example": "some-user@some-company-cloud.com"
    },
    "ancestry": {
      "description": "The links to data, which constitute the inputs, from which this record instance is derived.",
      "title": "Ancestry",
      "$ref": "osdu:wks:AbstractLegalParentList:1.0.0"
    },
    "meta": {
      "description": "The Frame of Reference meta data section linking the named properties to self-contained definitions.",
      "title": "Frame of Reference Meta Data",
      "type": "array",
      "items": {
        "$ref": "osdu:wks:AbstractMetaItem:1.0.0"
      }
    },
    "data": {
      "allOf": [
        {
          "$ref": "osdu:wks:AbstractCommonResources:1.0.1"
        },
        {
          "$ref": "osdu:wks:AbstractReferenceType:1.0.0"
        },
        {
          "type": "object",
          "properties": {},
          "title": "IndividualProperties"
        },
        {
          "type": "object",
          "properties": {
            "ExtensionProperties": {
              "type": "object"
            }
          },
          "title": "ExtensionProperties"
        }
      ]
    }
  },
  "required": [
    "kind",
    "acl",
    "legal"
  ],
  "additionalProperties": false,
  "x-osdu-review-status": "Pending",
  "x-osdu-governance-model": "OPEN",
  "x-osdu-governance-authorities": [
    "OSDU"
  ],
  "x-osdu-virtual-properties": {
    "data.VirtualProperties.DefaultName": {
      "type": "string",
      "priority": [
        {
          "path": "data.Name"
        }
      ]
    }
  },
  "x-osdu-inheriting-from-kind": [
    {
      "name": "ReferenceType",
      "kind": "osdu:wks:AbstractReferenceType:1.0.0"
    }
  ]
}

=== KiranBedre/osdu-spi-rafs-ddms/app/models/examples/reservoir_simulation_rock_physics_model.json
[
  {
    "id": "namespace:work-product-component--ReservoirSimulationRockPhysicsModel:volve-eclpise-rockphysics-1",
    "data": {
      "CompressibilityModelTypeID": "namespace:reference-data--CompressibilityModelType:SomeUniqueCompressibilityModelTypeID:",
      "ThermalModelTypeID": "namespace:reference-data--ThermalModelType:SomeUniqueThermalModelTypeID:",
      "BasisOfModelling": {
        "CompressibilityModelInputSampleAnalysisIDs": [
          "namespace:work-product-component--SamplesAnalysis:SamplesAnalysis-911bb71f-06ab-4deb-8e68-b8c9229dc76b:"
        ],
        "CompressibilityModelInputDataCollectionID": "namespace:work-product-component--PersistedCollection:PersistedCollection-911bb71f-06ab-4deb-8e68-b8c9229dc76b:",
        "ThermalModelInputSampleAnalysisIDs": [
          "namespace:work-product-component--SamplesAnalysis:SamplesAnalysis-911bb71f-06ab-4deb-8e68-b8c9229dc76b:"
        ],
        "ThermalModelInputDataCollectionID": "namespace:work-product-component--PersistedCollection:PersistedCollection-911bb71f-06ab-4deb-8e68-b8c9229dc76b:",
        "ModellingApplicationsUsed": [
          "Example ModellingApplicationsUsed"
        ],
        "IntendedWorkflowUsageIDs": [
          "namespace:reference-data--WorkflowUsageType:All:"
        ]
      },
      "ParentModelID": "namespace:work-product-component--ReservoirSimulationRockPhysicsModel:f3e451d1-9d49-559f-93d8-2e36722016fb:",
      "DatePublished": "2020-02-13T09:13:15.55Z",
      "Remarks": [
        {
          "RemarkSequenceNumber": 1,
          "Remark": "Example Remark",
          "RemarkSource": "Example Remark Source",
          "RemarkDate": "2020-02-13"
        }
      ]
    },
    "kind": "osdu:wks:work-product-component--ReservoirSimulationRockPhysicsModel:1.0.0",
    "acl": {
      "viewers": [
        "someone@company.com"
      ],
      "owners": [
        "someone@company.com"
      ]
    },
    "legal": {
      "legaltags": [
        "namespace-default-legal"
      ],
      "otherRelevantDataCountries": [
        "US"
      ]
    }
  }
]

=== KiranBedre/osdu-spi-rafs-ddms/tests/integration/data/v2/simulation_rock_physics/rsrp.json
{
    "kind": "{schema_authority}:wks:work-product-component--ReservoirSimulationRockPhysicsModel:{wpc_version}",
    "acl": {
        "viewers": [
            "{acl_viewers}"
        ],
        "owners": [
            "{acl_owners}"
        ]
    },
    "legal": {
        "legaltags": [
            "{legal_tag}"
        ],
        "otherRelevantDataCountries": [
            "US"
        ],
        "status": "compliant"
    },
    "data": {
            "CompressibilityModelTypeID": "{data_partition_id}:reference-data--CompressibilityModelType:BulkCompressibility:",
            "ThermalModelTypeID": "{data_partition_id}:reference-data--ThermalModelType:GeometricMeanModel:",
            "ParentModelID": "{data_partition_id}:work-product-component--ReservoirSimulationRockPhysicsModel:ParentRecord:",
            "DatePublished": "2024-01-01",
            "Name": "Reservoir Simulation Rock Physics Model",
            "BasisOfModelling": {
                "CompressibilityModelInputSampleAnalysisIDs": [
                    "{data_partition_id}:work-product-component--SamplesAnalysis:SamplesAnalysis-sample_test:"
                ],
                "CompressibilityModelInputDataCollectionID": "{data_partition_id}:work-product-component--PersistedCollection:CollectionRecord:",
                "ThermalModelInputSampleAnalysisIDs": [
                    "{data_partition_id}:work-product-component--SamplesAnalysis:SamplesAnalysis-sample_test:"
                ],
                "ThermalModelInputDataCollectionID": "{data_partition_id}:work-product-component--PersistedCollection:CollectionRecord:",
                "ModellingApplicationsUsed": [
                    "Eclipse"
                ],
                "IntendedWorkflowUsageIDs": [
                    "{data_partition_id}:reference-data--WorkflowUsageType:SeismicProcessing:"
                ]
            },
            "Remarks": [
                {
                "RemarkSequenceNumber":1,
                "Remark":"Remark",
                "RemarkSource":"Remark Source",
                "RemarkDate":"2025-01-01"
                }
            ]
    }
}

=== KiranBedre/osdu-spi-rafs-ddms/app/models/examples/fluid_model.json
[
    {
        "id": "namespace:work-product-component--FluidModel:4c633952-dff6-5eb3-883e-3cbe77810204",
        "kind": "osdu:wks:work-product-component--FluidModel:1.0.0",
        "version": 1562066009929332,
        "acl": {
            "owners": [
                "someone@company.com"
            ],
            "viewers": [
                "someone@company.com"
            ]
        },
        "legal": {
            "legaltags": [
                "Example legaltags"
            ],
            "otherRelevantDataCountries": [
                "US"
            ],
            "status": "compliant"
        },
        "tags": {
            "NameOfKey": "String value"
        },
        "createTime": "2020-12-16T11:46:20.163Z",
        "createUser": "some-user@some-company-cloud.com",
        "modifyTime": "2020-12-16T11:52:24.477Z",
        "modifyUser": "some-user@some-company-cloud.com",
        "ancestry": {
            "parents": []
        },
        "meta": [],
        "data": {
            "FluidModelTypeID": "namespace:reference-data--FluidModelType:BlackOil:",
            "BasisOfModelling": {
                "InputDataCollectionID": "namespace:work-product-component--PersistedCollection:f3e451d1-9d49-559f-93d8-2e36722016fb:",
                "ModelPropertyFormulationMethods": [
                    {
                        "ModelPropertyTypeID": "namespace:reference-data--FluidModelPropertyType:Density:",
                        "ModelPropertyFormulationMethodID": "namespace:reference-data--FluidModelPropertyFormulationMethod:PengRobinson:"
                    }
                ],
                "ModellingApplicationsUsed": [
                    "PVTsim Nova 5.0"
                ],
                "IntendedWorkflowUsageIDs": [
                    "namespace:reference-data--WorkflowUsageType:ReservoirSimulation:"
                ],
                "IsOptimizedForEnhancedRecoveryStudies": false,
                "IsModelPvtOptimized": true,
                "IsModelViscosityOptimized": true,
                "IsCompositionLumped": true,
                "ComponentCount": 8
            },
            "ParentModelID": "namespace:work-product-component--FluidModel:parent-model-id:",
            "DatePublished": "2020-02-13T09:13:15.55Z",
            "ModellingContacts": [
                {
                    "EmailAddress": "pvt-analyst@company.com",
                    "Name": "PVT Analyst"
                }
            ],
            "ModelAreaOfInterestIDs": [
                "namespace:master-data--Reservoir:reservoir-123:"
            ],
            "IsApplicableForThermalSimulation": false,
            "FluidModelSaturationTypeID": "namespace:reference-data--FluidModelSaturationType:BubblePoint:",
            "HasVariableDepthFluidProperties": false,
            "Remarks": [
                {
                    "RemarkSequenceNumber": 1,
                    "Remark": "Black oil model for reservoir simulation",
                    "RemarkSource": "PVT Lab",
                    "RemarkDate": "2020-02-13"
                }
            ],
            "ExtensionProperties": {}
        }
    }
]
